version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - .:/app
    command: gunicorn wsgi:app --bind 0.0.0.0:8000
    expose:
      - "8000"
