services:
  web:
    image: python:3.9
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install -r requirements.txt && gunicorn wsgi:app --bind 0.0.0.0:8000"
    expose:
      - "8000"
